"""initial

Revision ID: 7bc3c9ac52cc
Revises: 
Create Date: 2026-06-29 15:07:15.869505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc3c9ac52cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_seeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('encrypted_mnemonic', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_seeds_id'), 'master_seeds', ['id'], unique=False)
    op.create_index(op.f('ix_master_seeds_name'), 'master_seeds', ['name'], unique=True)
    op.create_table('bot_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('master_seed_id', sa.Integer(), nullable=True),
    sa.Column('btc_address', sa.String(), nullable=True),
    sa.Column('eth_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['master_seed_id'], ['master_seeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_wallets_id'), 'bot_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_bot_wallets_name'), 'bot_wallets', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_wallets_name'), table_name='bot_wallets')
    op.drop_index(op.f('ix_bot_wallets_id'), table_name='bot_wallets')
    op.drop_table('bot_wallets')
    op.drop_index(op.f('ix_master_seeds_name'), table_name='master_seeds')
    op.drop_index(op.f('ix_master_seeds_id'), table_name='master_seeds')
    op.drop_table('master_seeds')
    # ### end Alembic commands ###
